name: small git push

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # git clone (this)
      - name: git setting
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USER }}"
      - name: Commit files
        run: |
          TZ=-9 date '+%Y/%m/%d (JST)' >dummy
          git add .
          git commit -m "Update dummy by Github Actions" -a
          git pull
          git push
