name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # git clone this
      - name: git setting
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "shimajima-eiji"
      - name: Commit files
        run: |
          echo "test" >dummy
          git add .
          git commit -m "Add dummy" -a
          git pull
          git push
